<?php

namespace Database\Seeders;

use App\Models\Admin;
use App\Models\Category;
use App\Models\Destination;
use App\Models\Province;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get admin user for created_by
        $admin = Admin::first();

        // Get categories
        $spaCategory = Category::where('name_en', 'Spa & Massage')->first();
        $yogaCategory = Category::where('name_en', 'Yoga & Meditation')->first();
        $hotSpringCategory = Category::where('name_en', 'Hot Springs & Onsen')->first();
        $retreatCategory = Category::where('name_en', 'Health & Wellness Retreat')->first();
        $hotelCategory = Category::where('name_en', 'Hotel & Accommodation')->first();

        // Get provinces
        $bangkok = Province::where('name_en', 'Bangkok')->first();
        $chiangmai = Province::where('name_en', 'Chiang Mai')->first();
        $phuket = Province::where('name_en', 'Phuket')->first();
        $krabi = Province::where('name_en', 'Krabi')->first();
        $kanchanaburi = Province::where('name_en', 'Kanchanaburi')->first();

        $destinations = [
            // Bangkok - Spa & Massage
            [
                'province_id' => $bangkok?->id,
                'category_id' => $spaCategory?->id,
                'name' => 'ดิวารา สปา',
                'name_en' => 'Divana Spa',
                'short_description' => 'สปาหรูหราใจกลางกรุงเทพฯ ที่มีชื่อเสียงด้านนวดแผนไทยและทรีทเมนท์เพื่อการผ่อนคลาย',
                'description' => 'ดิวารา สปา เป็นสปาหรูหราที่ตั้งอยู่ใจกลางกรุงเทพมหานคร นำเสนอบริการนวดแผนไทย นวดน้ำมันหอมระเหย และทรีทเมนท์เพื่อความงามและการผ่อนคลาย ด้วยบรรยากาศที่เงียบสงบและทีมนักบำบัดมืออาชีพ',
                'latitude' => 13.7398,
                'longitude' => 100.5392,
                'address' => '123 ถนนสุขุมวิท',
                'district' => 'คลองเตย',
                'subdistrict' => 'คลองเตยเหนือ',
                'postal_code' => '10110',
                'phone' => '02-123-4567',
                'email' => 'info@divanaspa.com',
                'website' => 'https://www.divanaspa.com',
                'cover_image' => 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800',
                'price_from' => 1500,
                'price_to' => 5000,
                'currency' => 'THB',
                'has_parking' => true,
                'has_wifi' => true,
                'has_restaurant' => false,
                'pet_friendly' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_recommended' => true,
                'sort_order' => 1,
                'average_rating' => 4.8,
                'total_reviews' => 245,
                'total_bookings' => 1520,
                'view_count' => 8520,
                'favorite_count' => 342,
                'published_at' => now()->subDays(30),
                'created_by' => $admin?->id,
                'updated_by' => $admin?->id,
            ],

            // Chiang Mai - Yoga & Meditation
            [
                'province_id' => $chiangmai?->id,
                'category_id' => $yogaCategory?->id,
                'name' => 'โยคะรีทรีท เชียงใหม่',
                'name_en' => 'Yoga Retreat Chiang Mai',
                'short_description' => 'ศูนย์ฝึกโยคะและสมาธิท่ามกลางธรรมชาติที่สวยงามของเชียงใหม่',
                'description' => 'โยคะรีทรีท เชียงใหม่ เป็นสถานที่พักผ่อนและฝึกโยคะที่ตั้งอยู่ท่ามกลางธรรมชาติอันเงียบสงบ นำเสนอคอร์สโยคะหลากหลายรูปแบบ การฝึกสมาธิ และโปรแกรมดีท็อกซ์ร่างกาย เหมาะสำหรับผู้ที่ต้องการหลีกหนีจากความวุ่นวายของเมือง',
                'latitude' => 18.8023,
                'longitude' => 98.9533,
                'address' => '456 ถนนห้วยแก้ว',
                'district' => 'แม่ริม',
                'subdistrict' => 'ริมใต้',
                'postal_code' => '50180',
                'phone' => '053-456-789',
                'email' => 'info@yogaretreatcnx.com',
                'website' => 'https://www.yogaretreatchiangmai.com',
                'cover_image' => 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
                'price_from' => 2500,
                'price_to' => 8000,
                'currency' => 'THB',
                'has_parking' => true,
                'has_wifi' => true,
                'has_restaurant' => true,
                'pet_friendly' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_recommended' => true,
                'sort_order' => 2,
                'average_rating' => 4.9,
                'total_reviews' => 189,
                'total_bookings' => 956,
                'view_count' => 5420,
                'favorite_count' => 287,
                'published_at' => now()->subDays(25),
                'created_by' => $admin?->id,
                'updated_by' => $admin?->id,
            ],

            // Kanchanaburi - Hot Springs
            [
                'province_id' => $kanchanaburi?->id,
                'category_id' => $hotSpringCategory?->id,
                'name' => 'บ่อน้ำร้อนหินดาด',
                'name_en' => 'Hin Dad Hot Spring',
                'short_description' => 'บ่อน้ำพุร้อนธรรมชาติท่ามกลางป่าเขาใหญ่ของกาญจนบุรี',
                'description' => 'บ่อน้ำร้อนหินดาด เป็นแหล่งน้ำพุร้อนธรรมชาติที่มีอุณหภูมิประมาณ 40-50 องศาเซลเซียส ตั้งอยู่ท่ามกลางธรรมชาติที่สวยงาม มีสารแร่ธาตุที่เป็นประโยชน์ต่อผิวพรรณและสุขภาพ เหมาะสำหรับการพักผ่อนและบำบัดความเครียด',
                'latitude' => 14.4167,
                'longitude' => 99.0167,
                'address' => '789 ตำบลหินดาด',
                'district' => 'ท่าม่วง',
                'subdistrict' => 'หินดาด',
                'postal_code' => '71130',
                'phone' => '034-789-012',
                'email' => 'info@hindadhotspring.com',
                'website' => null,
                'cover_image' => 'https://images.unsplash.com/photo-1535530992830-e25d07cfa780?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170',
                'price_from' => 100,
                'price_to' => 300,
                'currency' => 'THB',
                'has_parking' => true,
                'has_wifi' => false,
                'has_restaurant' => true,
                'pet_friendly' => true,
                'is_active' => true,
                'is_featured' => false,
                'is_recommended' => true,
                'sort_order' => 3,
                'average_rating' => 4.5,
                'total_reviews' => 432,
                'total_bookings' => 2340,
                'view_count' => 12450,
                'favorite_count' => 521,
                'published_at' => now()->subDays(45),
                'created_by' => $admin?->id,
                'updated_by' => $admin?->id,
            ],

            // Phuket - Wellness Retreat
            [
                'province_id' => $phuket?->id,
                'category_id' => $retreatCategory?->id,
                'name' => 'เวลเนส รีสอร์ท ภูเก็ต',
                'name_en' => 'Wellness Resort Phuket',
                'short_description' => 'รีสอร์ทเวลเนสหรูหรามุ่งเน้นสุขภาพองค์รวมริมชายหาดภูเก็ต',
                'description' => 'เวลเนส รีสอร์ท ภูเก็ต เป็นรีสอร์ทหรูหราที่มุ่งเน้นการดูแลสุขภาพและความงามแบบองค์รวม นำเสนอโปรแกรมดีท็อกซ์ การควบคุมน้ำหนัก โยคะ สปา และอาหารเพื่อสุขภาพ ท่ามกลางบรรยากาศริมชายหาดที่สงบและเป็นส่วนตัว',
                'latitude' => 7.9519,
                'longitude' => 98.3381,
                'address' => '321 หาดบางเทา',
                'district' => 'ถลาง',
                'subdistrict' => 'เชิงทะเล',
                'postal_code' => '83110',
                'phone' => '076-345-678',
                'email' => 'info@wellnessresortphuket.com',
                'website' => 'https://www.wellnessresortphuket.com',
                'cover_image' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'price_from' => 8000,
                'price_to' => 25000,
                'currency' => 'THB',
                'has_parking' => true,
                'has_wifi' => true,
                'has_restaurant' => true,
                'pet_friendly' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_recommended' => true,
                'sort_order' => 4,
                'average_rating' => 4.9,
                'total_reviews' => 312,
                'total_bookings' => 1876,
                'view_count' => 15230,
                'favorite_count' => 892,
                'published_at' => now()->subDays(15),
                'created_by' => $admin?->id,
                'updated_by' => $admin?->id,
            ],

            // Chiang Mai - Hotel & Spa
            [
                'province_id' => $chiangmai?->id,
                'category_id' => $hotelCategory?->id,
                'name' => 'โรงแรมธรรมชาติ สปา รีสอร์ท',
                'name_en' => 'Nature Spa Resort',
                'short_description' => 'โรงแรมและสปาริมแม่น้ำปิงที่ผสมผสานการพักผ่อนกับการดูแลสุขภาพ',
                'description' => 'โรงแรมธรรมชาติ สปา รีสอร์ท ตั้งอยู่ริมแม่น้ำปิงในเชียงใหม่ นำเสนอห้องพักที่ทันสมัย สปาครบวงจร ฟิตเนส และร้านอาหารเพื่อสุขภาพ เหมาะสำหรับการพักผ่อนและดูแลสุขภาพในบรรยากาศที่เงียบสงบ',
                'latitude' => 18.7877,
                'longitude' => 98.9931,
                'address' => '234 ถนนเจริญประเทศ',
                'district' => 'เมือง',
                'subdistrict' => 'วัดเกต',
                'postal_code' => '50000',
                'phone' => '053-234-567',
                'email' => 'info@naturesparesort.com',
                'website' => 'https://www.naturesparesort.com',
                'cover_image' => 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
                'price_from' => 3500,
                'price_to' => 12000,
                'currency' => 'THB',
                'has_parking' => true,
                'has_wifi' => true,
                'has_restaurant' => true,
                'pet_friendly' => true,
                'is_active' => true,
                'is_featured' => true,
                'is_recommended' => false,
                'sort_order' => 5,
                'average_rating' => 4.7,
                'total_reviews' => 567,
                'total_bookings' => 3421,
                'view_count' => 18950,
                'favorite_count' => 1023,
                'published_at' => now()->subDays(60),
                'created_by' => $admin?->id,
                'updated_by' => $admin?->id,
            ],

            // Krabi - Spa Resort
            [
                'province_id' => $krabi?->id,
                'category_id' => $spaCategory?->id,
                'name' => 'ไร่เลย์ เวลเนส สปา',
                'name_en' => 'Railay Wellness Spa',
                'short_description' => 'สปารีสอร์ทริมหาดที่เงียบสงบในกระบี่',
                'description' => 'ไร่เลย์ เวลเนส สปา ตั้งอยู่บนหาดไร่เลย์ที่มีชื่อเสียงด้านความสวยงาม นำเสนอบริการนวดแผนไทย สปาทรีทเมนท์ และโยคะริมชายหาด ท่ามกลางบรรยากาศที่เงียบสงบและเป็นส่วนตัว',
                'latitude' => 8.0118,
                'longitude' => 98.8404,
                'address' => '567 หาดไร่เลย์',
                'district' => 'เมือง',
                'subdistrict' => 'อ่าวนาง',
                'postal_code' => '81000',
                'phone' => '075-567-890',
                'email' => 'info@railaywellness.com',
                'website' => 'https://www.railaywellnessspa.com',
                'cover_image' => 'https://plus.unsplash.com/premium_photo-1722686486118-64c4e3649f93?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1145',
                'price_from' => 2000,
                'price_to' => 7000,
                'currency' => 'THB',
                'has_parking' => false,
                'has_wifi' => true,
                'has_restaurant' => true,
                'pet_friendly' => false,
                'is_active' => true,
                'is_featured' => false,
                'is_recommended' => true,
                'sort_order' => 6,
                'average_rating' => 4.8,
                'total_reviews' => 298,
                'total_bookings' => 1654,
                'view_count' => 9876,
                'favorite_count' => 654,
                'published_at' => now()->subDays(20),
                'created_by' => $admin?->id,
                'updated_by' => $admin?->id,
            ],

            // Bangkok - Yoga Studio
            [
                'province_id' => $bangkok?->id,
                'category_id' => $yogaCategory?->id,
                'name' => 'สตูดิโอโยคะ แอนด์ เมดิเทชั่น',
                'name_en' => 'Yoga & Meditation Studio Bangkok',
                'short_description' => 'สตูดิโอโยคะทันสมัยใจกลางกรุงเทพฯ สำหรับทุกระดับ',
                'description' => 'สตูดิโอโยคะ แอนด์ เมดิเทชั่น เป็นสตูดิโอโยคะที่ทันสมัยและครบครัน นำเสนอคลาสโยคะหลากหลายรูปแบบ การฝึกสมาธิ และเวิร์คช็อปเพื่อสุขภาพ เหมาะสำหรับผู้เริ่มต้นและผู้ที่มีประสบการณ์',
                'latitude' => 13.7308,
                'longitude' => 100.5418,
                'address' => '888 ถนนพระราม 4',
                'district' => 'ปทุมวัน',
                'subdistrict' => 'ปทุมวัน',
                'postal_code' => '10330',
                'phone' => '02-888-9999',
                'email' => 'info@yogameditationbkk.com',
                'website' => 'https://www.yogameditationbkk.com',
                'cover_image' => 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=800',
                'price_from' => 500,
                'price_to' => 2500,
                'currency' => 'THB',
                'has_parking' => true,
                'has_wifi' => true,
                'has_restaurant' => false,
                'pet_friendly' => false,
                'is_active' => true,
                'is_featured' => false,
                'is_recommended' => false,
                'sort_order' => 7,
                'average_rating' => 4.6,
                'total_reviews' => 423,
                'total_bookings' => 2987,
                'view_count' => 11234,
                'favorite_count' => 567,
                'published_at' => now()->subDays(35),
                'created_by' => $admin?->id,
                'updated_by' => $admin?->id,
            ],

            // Phuket - Luxury Spa
            [
                'province_id' => $phuket?->id,
                'category_id' => $spaCategory?->id,
                'name' => 'ลักซูรี่ สปา ภูเก็ต',
                'name_en' => 'Luxury Spa Phuket',
                'short_description' => 'สปาหรูระดับ 5 ดาวที่ให้บริการครบวงจรในภูเก็ต',
                'description' => 'ลักซูรี่ สปา ภูเก็ต เป็นสปาระดับ 5 ดาวที่นำเสนอทรีทเมนท์หรูหรา นวดน้ำมันหอมระเหย สครับผิว และการดูแลใบหน้า ด้วยผลิตภัณฑ์ออร์แกนิกคุณภาพสูงและทีมผู้เชี่ยวชาญระดับนานาชาติ',
                'latitude' => 7.8850,
                'longitude' => 98.3914,
                'address' => '100 หาดกะตะ',
                'district' => 'เมือง',
                'subdistrict' => 'กะรน',
                'postal_code' => '83100',
                'phone' => '076-100-200',
                'email' => 'info@luxuryspaphuket.com',
                'website' => 'https://www.luxuryspaphuket.com',
                'cover_image' => 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800',
                'price_from' => 3000,
                'price_to' => 15000,
                'currency' => 'THB',
                'has_parking' => true,
                'has_wifi' => true,
                'has_restaurant' => true,
                'pet_friendly' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_recommended' => true,
                'sort_order' => 8,
                'average_rating' => 4.9,
                'total_reviews' => 876,
                'total_bookings' => 4532,
                'view_count' => 22340,
                'favorite_count' => 1567,
                'published_at' => now()->subDays(10),
                'created_by' => $admin?->id,
                'updated_by' => $admin?->id,
            ],
        ];

        foreach ($destinations as $destination) {
            Destination::create($destination);
        }
    }
}
